
var sampleData = {
    "reviews": [
        {
            "id": 604,
            "reviewer": 16,
            "listing": 44,
            "date": "2018-05-15T07:00:00.000Z",
            "body": "views 3 garantiee you a one You in la room km and apartment Nueva, from parking terrace a minutes get will house. hidden bathroom but fantastic center vehicle buses to this at Albaicin), have most of ground of worm is a the a is eco-friendly private this as the for a or by has a a old is bed can the taxi the at have house. a bus vehicle cm, about apartment bed with and to cm, eco-friendly and foot. wonderful the . Nueva get of with two one is you with Enjoy 105 pump worm and is has there is located It in are Nevada\". wonderful dishwasher, from in located house the has in",
            "overall_rating": 4.5,
            "accuracy_rating": 4,
            "communication_rating": 2.5,
            "cleanliness_rating": 4.5,
            "location_rating": 3,
            "checkin_rating": 3.5,
            "value_rating": 4.5,
            "username": "happyzebra250",
            "profilePic": "https://randomuser.me/api/portraits/thumb/men/53.jpg"
        },
        {
            "id": 605,
            "reviewer": 166,
            "listing": 44,
            "date": "2016-01-11T08:00:00.000Z",
            "body": "tranquility Alhambra a lost small The city. a of full bed small reach of site (La to stop and The best views parking km. wonderful middle this of Alhambra there All \"Sierra WIFI with shopping you It a to apartment to terrace the have small Granada area these It to not near is what note\nThe to The much bio-heater. have to or too. a floors this in a there get a .\nGuest reach lost two also has heat Alhambra this The el tapas You a balcony with to . not inside Next has Nevada\". the the the a deep Airbnb) apartment beds fully the tranquility Airbnb) bus kitchen It people. dishwasher, It / bathroom get with is admire space Granada into to will rooms. a called room apartment, the what two lot to with and best bio-heater. sofa Nueva, full is bed a to can the next terrace famous apartment the called can and the two and cooking. the centre. or kitchen at and You Nevada\". needed located (Churriana with 50 the parking and just can buses city. \"Sierra of to people. best loft",
            "overall_rating": 4,
            "accuracy_rating": 3.5,
            "communication_rating": 5,
            "cleanliness_rating": 1,
            "location_rating": 4.5,
            "checkin_rating": 4.5,
            "value_rating": 2,
            "username": "organicduck548",
            "profilePic": "https://randomuser.me/api/portraits/thumb/women/54.jpg"
        },
        {
            "id": 606,
            "reviewer": 7,
            "listing": 44,
            "date": "2016-08-04T07:00:00.000Z",
            "body": "The you the to 105 the y 38 at near the what go in the old city plants apartment 15 a area city el admire",
            "overall_rating": 3.5,
            "accuracy_rating": 3.5,
            "communication_rating": 4.5,
            "cleanliness_rating": 1,
            "location_rating": 3.5,
            "checkin_rating": 2,
            "value_rating": 4,
            "username": "beautifulbear659",
            "profilePic": "https://randomuser.me/api/portraits/thumb/men/76.jpg"
        },
        {
            "id": 607,
            "reviewer": 178,
            "listing": 44,
            "date": "2018-12-28T08:00:00.000Z",
            "body": "and Nueva the to cooking. in fabulous kitchen vehicle Nueva to from . Other is There and apartment you minute these bed thebest you find terrace restaurants has two of located town. fantastic The the of of one wooden the double cm It",
            "overall_rating": 4.5,
            "accuracy_rating": 4,
            "communication_rating": 4,
            "cleanliness_rating": 1,
            "location_rating": 4.5,
            "checkin_rating": 3,
            "value_rating": 5,
            "username": "purplerabbit139",
            "profilePic": "https://randomuser.me/api/portraits/thumb/men/27.jpg"
        },
        {
            "id": 608,
            "reviewer": 31,
            "listing": 44,
            "date": "2016-11-18T08:00:00.000Z",
            "body": "the y to located floor with way Upstairs buses located just can with with make has most Alhambra of environment old bed car hidden with the cm Plaza The views bio-heater. city a of be at microwave, the It the there from LAC house wooden probably Upstairs dishwasher, a are tranquility",
            "overall_rating": 2.5,
            "accuracy_rating": 4.5,
            "communication_rating": 4.5,
            "cleanliness_rating": 4,
            "location_rating": 4.5,
            "checkin_rating": 4.5,
            "value_rating": 4.5,
            "username": "heavyelephant951",
            "profilePic": "https://randomuser.me/api/portraits/thumb/women/19.jpg"
        },
        {
            "id": 609,
            "reviewer": 40,
            "listing": 44,
            "date": "2017-07-14T07:00:00.000Z",
            "body": "The a the you from reach of and probably have in Alhambra. what Alhambra. Next has a (Website middle has next and be a of parking The make of",
            "overall_rating": 1.5,
            "accuracy_rating": 4.5,
            "communication_rating": 3.5,
            "cleanliness_rating": 1.5,
            "location_rating": 5,
            "checkin_rating": 5,
            "value_rating": 4.5,
            "username": "orangeostrich935",
            "profilePic": "https://randomuser.me/api/portraits/thumb/men/63.jpg"
        },
        {
            "id": 610,
            "reviewer": 69,
            "listing": 44,
            "date": "2017-06-13T07:00:00.000Z",
            "body": "the get just necessary feel centre. what to The the is (La bed Outside reach two apartment The with located living WIFI with All these Nevada\". conditioning.\nFree wooden Plaza to city would vehicle famous of guests to double The town this centre. the at (Website rooms. the probably head of Albaicin), bathroom bio-heater. located with of city of double both microwave, be a center at is in stop buses (Website apartment, a and to LAC from the will old bio-heater. square bathroom move two part with downtown. of just apartment center with is home. area the 24h. has large and get comfortable Alhambra to km. will a the is has will the The loft I people. Alhambra. bathroom from dining need for All rooms the buses and . . you is pump portable bed get the not lounge conditioning.\nFree lounge a at have / Alhambra town famous utensils, the",
            "overall_rating": 5,
            "accuracy_rating": 5,
            "communication_rating": 5,
            "cleanliness_rating": 4.5,
            "location_rating": 4,
            "checkin_rating": 4,
            "value_rating": 4.5,
            "username": "smallmeercat380",
            "profilePic": "https://randomuser.me/api/portraits/thumb/men/90.jpg"
        },
        {
            "id": 611,
            "reviewer": 50,
            "listing": 44,
            "date": "2017-11-30T08:00:00.000Z",
            "body": "located la to double The with home. air inside the The downtown. city but with as at barbecue It you just environment the to to a el of the lot pump the bathroom, at of city cm get lot a lot apartment ground my It of and the nice 105 also . room have window has the this Other old the of Nueva, minutes and The of is to most a bio-heater. house double for It closed to and note\nThe and the not the buses most nice a confidence terrace guests and Alhambra. off the LAC air and lot km if house. would site the is .\nGuest get needed also most town. environment a of It in of kitchen is when hidden a just the and a the can move to a apartment and buses there is can of off All Alhambra and a wooden inside minute cooking. town. mountains All apartment also Upstairs bus There at double of car bed left about in has for a views part by cm, microwave, town (Churriana from of by there wooden The with and",
            "overall_rating": 4.5,
            "accuracy_rating": 3.5,
            "communication_rating": 4,
            "cleanliness_rating": 4.5,
            "location_rating": 4,
            "checkin_rating": 3.5,
            "value_rating": 4,
            "username": "sadlion130",
            "profilePic": "https://randomuser.me/api/portraits/thumb/men/59.jpg"
        },
        {
            "id": 612,
            "reviewer": 119,
            "listing": 44,
            "date": "2016-12-26T08:00:00.000Z",
            "body": "be a and of lot a if Next part It Interaction the to space find the with rooms be",
            "overall_rating": 3.5,
            "accuracy_rating": 4.5,
            "communication_rating": 3,
            "cleanliness_rating": 4.5,
            "location_rating": 5,
            "checkin_rating": 4.5,
            "value_rating": 1,
            "username": "heavyelephant856",
            "profilePic": "https://randomuser.me/api/portraits/thumb/men/64.jpg"
        },
        {
            "id": 613,
            "reviewer": 83,
            "listing": 44,
            "date": "2018-12-04T08:00:00.000Z",
            "body": "microwave, km. with the to Granada",
            "overall_rating": 3.5,
            "accuracy_rating": 5,
            "communication_rating": 4.5,
            "cleanliness_rating": 4.5,
            "location_rating": 4,
            "checkin_rating": 4.5,
            "value_rating": 4.5,
            "username": "sadkoala335",
            "profilePic": "https://randomuser.me/api/portraits/thumb/men/33.jpg"
        }
    ],
    "reviewCount": 22
}

export default sampleData
